# Generated by Django 5.2.5 on 2025-09-26 20:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre del Área')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Especialidad')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del Empleado')),
                ('paterno', models.CharField(max_length=30, verbose_name='Apellido Paterno del Empleado')),
                ('materno', models.CharField(max_length=30, verbose_name='Apellido Materno del Empleado')),
                ('run', models.CharField(max_length=12, verbose_name='RUN')),
                ('genero', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino'), ('o', 'Otro')], default='o', max_length=1)),
                ('cantHoras', models.PositiveIntegerField(default=20, verbose_name='Cantidad de Horas Trabajadas')),
                ('fechaNac', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento del Empleado')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boxApp.area')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='boxApp.especialidad')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['nombre', 'paterno', 'materno'],
            },
        ),
    ]
