# Generated by Django 5.2.5 on 2025-10-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='materno',
            field=models.CharField(blank=True, max_length=30, verbose_name='Apellido Materno del Empleado'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
