# Generated by Django 5.2.5 on 2025-10-20 20:34

import boxApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0002_alter_area_creado_alter_doctor_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(default='empleados/empleado.png', null=True, upload_to=boxApp.models.Empleado.generarNombre),
        ),
    ]
