# Generated by Django 5.2.6 on 2025-11-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0003_doctor_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID del Producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Producto')),
                ('stock', models.PositiveIntegerField(verbose_name='Cantidad de Stock')),
                ('hora_ingreso', models.DateField(verbose_name='Hora de Ingreso')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cantHoras',
            field=models.PositiveIntegerField(default=20, max_length=25, verbose_name='Cantidad de Horas Trabajadas'),
        ),
    ]
