# Generated by Django 5.2.6 on 2025-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxApp', '0004_producto_alter_doctor_canthoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cantHoras',
            field=models.PositiveIntegerField(default=20, verbose_name='Cantidad de Horas Trabajadas'),
        ),
    ]
